makefoo-ized + autoconf-ed

diff --git a/bashfoo b/bashfoo
--- a/bashfoo
+++ b/bashfoo
@@ -3,37 +3,56 @@
 
 show_help()
 {
-    echo "usage: bashfoo --eval-out | --libdir"
+    echo "usage: bashfoo --eval-out | --libdir | --bootstrap-script | --help"
     echo ""
-    echo "* bashfoo --eval-out"
+    echo "  * bashfoo --eval-out"
     echo "    outputs Bash script that shall be evaulated by bash script"
     echo "    to bootstrap bashfoo env in script"
-    echo "* bashfoo --libdir"
+    echo ""
+    echo "  * bashfoo --libdir"
     echo "    outputs bashfoo library path, one shall source bashfoo.sh from"
     echo "    this folder to bootstrap bashfoo env"
+    echo ""
+    echo "  * bashfoo --bootstrap-script"
+    echo "    outputs PATH of bashfoo bootstrap script"
+    echo ""
+    echo "bashfoo is reusable shell script function library."
+    echo "See http://idf2hotpo.pl/index.php/p/bashfoo."
 }
 
 show_eval()
 {
+    ensure_location_variables_initialized
+    
     echo "bashfoo_source_path=$bashfoo_source_path"
     echo "source $bashfoo_source_path/bashfoo.sh"    
 }
 
-bashfoo_bin_prefix=$(dirname $BASH_SOURCE)
+ensure_location_variables_initialized()
+{
+    if [ -n "$bashfoo_bin_prefix" ] ; then
+        return
+    fi
+    bashfoo_bin_prefix=$(dirname $BASH_SOURCE)
+    if [ -f "$bashfoo_bin_prefix/bashfoo.sh" ] ; then
+        bashfoo_libdir="$bashfoo_bin_prefix"
+        bashfoo_source_path="$bashfoo_bin_prefix/bashfoo.sh"
+    elif [ -f "$bashfoo_bin_prefix/../lib/bashfoo/bashfoo.sh" ] ; then
+        bashfoo_libdir="$bashfoo_bin_prefix/../lib/bashfoo"
+        bashfoo_source_path="$bashfoo_bin_prefix/../lib/bashfoo/bashfoo.sh"
+    else
+        echo "bashfoo: unable to find bashfoo libdir in $bashfoo_bin_prefix and in $bashfoo_bin_prefix/../lib/bashfoo" >&2
+        exit 1
+    fi
+}
 
-if [ -f "$bashfoo_bin_prefix/bashfoo.sh" ] ; then
-    bashfoo_source_path="$bashfoo_bin_prefix/bashfoo.sh"
-elif [ -f "$bashfoo_bin_prefix/../lib/bashfoo/bashfoo.sh" ] ; then
-    bashfoo_source_path="$bashfoo_bin_prefix/../lib/bashfoo/bashfoo.sh"
-else
-    echo "bashfoo: unable to find bashfoo libdir in $bashfoo_bin_prefix and in $bashfoo_bin_prefix/../lib/bashfoo" >&2
+if [ -z "$1" ] ; then
+    show_help
+    exit 1
 fi
 
 # args parse
 while [ -n "$1" ] ; do
-    maybe_show_auto_help "$1"
-    maybe_invoke_introspection "$@"
-    
     if [ "$1" = --help -o "$1" = "-h" ] ; then
         show_help
         exit
@@ -41,11 +60,16 @@ while [ -n "$1" ] ; do
         show_eval
         exit
     elif [ "$1" = --libdir ] ; then
+        ensure_location_variables_initialized
+        echo "$bashfoo_libdir"
+        exit
+    elif [ "$1" = --bootstrap-script  ] ; then
+        ensure_location_variables_initialized
         echo "$bashfoo_source_path"
         exit
     else
         (
-            echo "bashfoo: invalid argument $1"
+            echo "bashfoo: invalid argument -- $1"
             show_help
         ) >&2
         exit 1
